### ISSUE TITLE
Change MQTT state topic names

### ISSUE THREAD

**Issue by rohankapoorcom** [aderusha/HASwitchPlate#20]
Is it possible to break up the page and box number portion of the mqtt topic string?

from: `hasp/plate01/state/p[1].b[1]`
to: `hasp/plate01/state/p[1]/b[1]`

This would allow simplifying several of the automatons in home assistant so that they can do something like this rather than specifying each trigger manually per page
```
- alias: hasp_down_plate_p0_PageButton1Action
    trigger:
    - platform: mqtt
      topic: 'hasp/down_plate/state/+/.b[1]'
      payload: 'ON'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_down_plate_activepage'
        value: '{{states.input_number.hasp_down_plate_pagebutton1page.state|int}}'
```
